import { Metadata } from "next";

export const metadata: Metadata = {
  title: "This is  Hooks lesson",
  description: "Generated by create next app",
};
export default function Template({ children }: { children: React.ReactNode }) {
  return <div>{children}</div>;
}
